### ISSUE TITLE
Repeatedly crashes on iPhone

### ISSUE THREAD

**Issue by TahomaSoft** [shralpmeister/shralptide2#7]
**Describe the bug**

Was working fine, but now crashes repeatedly.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shralpmeister** [comment]
Please try uninstalling and reinstalling the app. Let me know if that resolves the issue or not.
