### ISSUE TITLE
Water level don’t match

### ISSUE THREAD

**Issue by MathieuHarton** [shralpmeister/shralptide2#8]
![IMG_0310](https://user-images.githubusercontent.com/33403239/60308165-9f733000-9915-11e9-96ed-b7019bdccf55.jpeg)

**Comment by shralpmeister** [comment]
Thanks for reporting this. I was able to reproduce this issue with units set to metric. The graph displays the correct level in meters but the table levels are incorrect. IPhone isn't affected by this issue.

**Comment by shralpmeister** [comment]
Fixed in next app store release.
