### ISSUE TITLE
sliding tide level bar 

### ISSUE THREAD

**Issue by makingthedrop** [shralpmeister/shralptide2#9]
**Describe the bug**
Sliding tide level bar registers "0.00" on any future dates. This has just started in the last couple weeks on my iphone 11, in both ios 14.1 and 14.2. Verified and replicated error on multiple buoys.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mparlee** [comment]
Just ran into this myself this morning. I will get a fix out ASAP. Thanks for reporting it!

**Comment by makingthedrop** [comment]
Right on! Need this for my surf coaching scheduling! Thx

Barry
www.centeredsurfing.com
